import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');
const BANNER_HEIGHT = 180;
// Fit two cards even when screens add extra padding (category pages, etc.)
const ITEM_WIDTH = (width - 40) / 2;
const pastelBg = '#FFF6FB';
const accent = '#FFD6E8';
const primary = '#FF4D79';
const gradientStart = '#FF8FB1';
const gradientEnd = '#FF4D79';
const text = '#2A0E23';
const muted = '#7A5368';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: pastelBg },
  gradientBg: {
    ...StyleSheet.absoluteFillObject,
  },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 14,
    backgroundColor: '#FF4D79',
    borderBottomWidth: 0,
  },
  headerLeft: { flex: 1 },
  hello: { fontSize: 13, color: 'rgba(255, 255, 255, 0.8)', opacity: 0.95 },
  username: { fontWeight: '800', color: 'white', fontSize: 15 },

  headerCenter: { flex: 2, paddingHorizontal: 10 },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingHorizontal: 12,
    height: 42,
    borderWidth: 1,
    borderColor: accent,
    shadowColor: '#FFB3CD',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },
  searchInput: { flex: 1, marginLeft: 8, color: text, fontSize: 14, fontWeight: '600' },

  headerRight: { flex: 0.5, alignItems: 'flex-end' },
  quickAction: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    shadowColor: '#FFB3CD',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 3,
  },

  bannerWrapper: {
    marginTop: 6,
    alignItems: 'center',
  },
  bannerImage: {
    width: width - 24,
    height: BANNER_HEIGHT,
    borderRadius: 16,
    marginHorizontal: 12,
    resizeMode: 'cover',
    shadowColor: '#FFB3CD',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 18,
    elevation: 6,
  },
  dots: {
    flexDirection: 'row',
    marginTop: 10,
    justifyContent: 'center',
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: accent,
    marginHorizontal: 4,
  },
  dotActive: { backgroundColor: primary },

  section: {
    marginTop: 16,
    paddingHorizontal: 14,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: text },
  sectionMore: { color: primary, fontSize: 13, fontWeight: '700' },
  sectionSub: { color: muted, fontSize: 12 },

  categoriesGrid: {
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: accent,
    shadowColor: '#FFB3CD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  categoryItem: {
    width: (width - 48) / 4,
    alignItems: 'center',
    marginVertical: 8,
  },
  categoryIconWrapper: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: '#FFF0F7',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: accent,
  },
  categoryIcon: { width: 38, height: 38, tintColor: primary, resizeMode: 'contain' },
  categoryLabel: { marginTop: 8, fontSize: 12, color: text, textAlign: 'center', fontWeight: '700' },

  flashCard: {
    width: 150,
    marginRight: 12,
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 10,
    shadowColor: '#FFB3CD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: accent,
  },
  flashImage: { width: '100%', height: 90, borderRadius: 10, resizeMode: 'cover' },
  flashName: { marginTop: 8, fontSize: 14, color: text, fontWeight: '700' },
  flashPrice: { marginTop: 6, color: primary, fontWeight: '800', fontSize: 15 },
  flashChip: {
    marginTop: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    backgroundColor: '#FFF0F7',
  },
  flashChipText: { color: primary, fontWeight: '700', fontSize: 12 },

  promoWrapper: {
    marginHorizontal: 12,
    marginTop: 14,
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#ff4d79',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 77, 121, 0.28)',
  },
  promoInner: {
    flexDirection: 'row',
    padding: 16,
    backgroundColor: 'transparent',
  },
  promoLeft: { flex: 1 },
  promoTitle: { fontSize: 18, fontWeight: '800', color: text },
  promoDesc: { fontSize: 13, color: muted, marginTop: 6, lineHeight: 18 },
  promoRow: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  rating: { flexDirection: 'row', alignItems: 'center', marginRight: 12 },
  ratingText: { marginLeft: 6, fontWeight: '800', color: text },
  shopNow: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 18,
    shadowColor: '#ff7aa3',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 4,
  },
  shopNowText: { color: primary, fontWeight: '800', fontSize: 13 },
  promoImageWrapper: {
    width: 110,
    height: 110,
    marginLeft: 12,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoGlow: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: 'rgba(255, 120, 170, 0.35)',
    shadowColor: '#ff5f95',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 24,
  },
  promoImage: {
    width: 100,
    height: 100,
    borderRadius: 14,
    resizeMode: 'cover',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },

  productsGrid: {
    paddingTop: 8,
    paddingBottom: 40,
  },
  productRow: {
    justifyContent: 'space-between',
  },
  productCard: {
    width: ITEM_WIDTH,
    backgroundColor: '#fff',
    borderRadius: 14,
    marginBottom: 12,
    overflow: 'hidden',
    shadowColor: '#FFB3CD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 1,
    borderColor: accent,
  },
  productImage: { width: '100%', height: ITEM_WIDTH, resizeMode: 'cover' },
  productMeta: { padding: 10 },
  productName: { fontSize: 14, color: text, fontWeight: '700' },
  productPrice: { marginTop: 8, fontSize: 15, fontWeight: '800', color: primary },

  bottomNav: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    height: 66,
    backgroundColor: '#fff',
    borderRadius: 30,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    elevation: 8,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: accent,
    shadowColor: '#FFB3CD',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
  },
  navItem: { alignItems: 'center', justifyContent: 'center' },
  addButtonWrapper: { alignItems: 'center', justifyContent: 'center', marginHorizontal: 2 },
  addButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FF4D79',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 7,
    marginBottom: 2,
  },
  navLabel: { fontSize: 11, color: muted, marginTop: 2, fontWeight: '700' },
  navBadge: {
    position: 'absolute',
    top: -6,
    right: -10,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 4,
    backgroundColor: primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navBadgeText: { color: '#fff', fontSize: 10, fontWeight: '800' },
});

// Export constants nếu cần dùng ở nơi khác
export { accent, BANNER_HEIGHT, ITEM_WIDTH, pastelBg, primary, width, gradientStart, gradientEnd, text, muted };
