import { StyleSheet } from "react-native";
import { heightPercentageToDP as hp, widthPercentageToDP as wp } from "react-native-responsive-screen";

// Home
export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#fff" },
  scroll: { flex: 1 },
  scrollContent: { paddingTop: hp("2.5%"), paddingBottom: hp("4%"), paddingHorizontal: wp("3%") },

  headerContainer: {
    backgroundColor: "#CC7861",
    paddingTop: hp("1.2%"),
    paddingBottom: hp("1.8%"),
    paddingHorizontal: wp("5%"),
  },
  header: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerGreeting: { fontSize: hp("2%"), color: "#FFE4E1", fontWeight: "500" },
  headerTitle: { fontSize: hp("3%"), color: "#FFFFFF", fontWeight: "700" },
  headerRight: { flexDirection: "row", alignItems: "center" },
  shopNamePressable: { marginTop: hp("0.4%") },
  headerIconButton: {
    marginLeft: wp("3.5%"),
    padding: wp("1.8%"),
    borderRadius: wp("3.8%"),
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  pressedIcon: { backgroundColor: "rgba(255,255,255,0.3)" },

  sectionPad: {
    width: "100%",
    marginTop: hp("2%"),
  },
  cardPressable: { borderRadius: 18, overflow: "hidden" },
  pressed: { opacity: 0.85 },
  pressedSoft: { opacity: 0.7 },

  flashCarousel: { alignSelf: "center" },
  flashCarouselContent: { paddingRight: wp("3%") },
  flashImage: { height: hp("20%"), borderRadius: 18, marginRight: wp("3%") },
  flashDots: { flexDirection: "row", justifyContent: "center", marginTop: hp("1.2%") },
  flashDot: { width: wp("2.6%"), height: wp("2.6%"), borderRadius: wp("1.3%"), marginHorizontal: wp("1%") },
  flashDotInactive: { backgroundColor: "rgba(252,165,165,0.45)" },
  flashDotActive: { backgroundColor: "#FB7185" },

  revenueCard: { borderRadius: 18, paddingVertical: hp("2.2%"), paddingHorizontal: wp("4.5%") },
  revenueRow: { flexDirection: "row", alignItems: "center" },
  revenueInfo: { flex: 1, marginLeft: wp("3%") },
  revenueIconWrap: {
    width: wp("12%"),
    height: wp("12%"),
    borderRadius: wp("6%"),
    backgroundColor: "#FFE4E8",
    justifyContent: "center",
    alignItems: "center",
  },
  revenueIconSmallWrap: {
    width: wp("9%"),
    height: wp("9%"),
    borderRadius: wp("4.5%"),
    backgroundColor: "#FFE7EA",
    justifyContent: "center",
    alignItems: "center",
    marginRight: wp("2.2%"),
  },
  revenueText: { fontSize: hp("2%"), fontWeight: "600", color: "#511414" },
  revenueNumber: { fontSize: hp("2.6%"), fontWeight: "700", color: "#7F1D1D", marginTop: hp("0.4%") },
  revenueDivider: { height: 1, backgroundColor: "rgba(255,255,255,0.6)", marginVertical: hp("1.6%") },
  revenueMetric: { flexDirection: "row", alignItems: "center" },
  revenueMetricText: { fontSize: hp("1.8%"), color: "#581C1C" },
  revenueMetricNumber: { fontWeight: "700" },

  productCard: { borderRadius: 18, overflow: "hidden" },
  productContent: { flexDirection: "row", alignItems: "center", paddingVertical: hp("2.2%"), paddingHorizontal: wp("4%") },
  productTextWrap: { flex: 1.35, paddingRight: wp("3%") },
  productTitle: { fontSize: hp("2.2%"), fontWeight: "700", color: "#2F2F31", marginBottom: hp("0.8%") },
  productDesc: { fontSize: hp("1.8%"), lineHeight: hp("2.4%"), color: "#3F3F46" },
  bold: { fontWeight: "700" },
  productArtWrap: { flex: 0.75, height: hp("16%") },
  productImage: { width: "100%", height: "100%", borderRadius: 16 },

  notificationCard: { borderRadius: 18, paddingVertical: hp("2%"), paddingHorizontal: wp("4.5%") },
  notificationHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: hp("1.4%") },
  notificationHeaderLeft: { flexDirection: "row", alignItems: "center" },
  notificationTitle: { marginLeft: wp("2%"), fontSize: hp("2%"), fontWeight: "700", color: "#BE123C" },
  notificationAction: { fontSize: hp("1.7%"), color: "#BE123C", fontWeight: "600" },
  notificationActionButton: { paddingHorizontal: wp("2.2%"), paddingVertical: hp("0.5%"), borderRadius: 999, backgroundColor: "rgba(255,255,255,0.55)" },
  notificationItem: { flexDirection: "row", alignItems: "flex-start", paddingVertical: hp("0.8%") },
  notificationItemDivider: { borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.7)" },
  notificationDot: { width: wp("2.5%"), height: wp("2.5%"), borderRadius: wp("1.25%"), backgroundColor: "#FB7185", marginRight: wp("3%"), marginTop: hp("0.6%") },
  notificationBody: { flex: 1 },
  notificationText: { fontSize: hp("1.8%"), color: "#1F2937", fontWeight: "600" },
  notificationTime: { fontSize: hp("1.6%"), color: "#6B7280", marginTop: hp("0.4%") },

  messageCard: { borderRadius: 18, paddingVertical: hp("2.2%"), paddingHorizontal: wp("5%") },
  messageHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  messageTitle: { fontSize: hp("2.2%"), fontWeight: "700", color: "#1F2937" },
  messageBadge: { paddingHorizontal: wp("3%"), paddingVertical: hp("0.6%"), backgroundColor: "rgba(255,255,255,0.7)", borderRadius: 999 },
  messageBadgeText: { fontSize: hp("1.5%"), fontWeight: "600", color: "#B91C1C" },
  messageList: { marginTop: hp("1.8%") },

  avatar: { width: hp("5.6%"), height: hp("5.6%"), borderRadius: 999, backgroundColor: "#fff" },
  commentRow: { flexDirection: "row", alignItems: "flex-start", marginBottom: hp("1.6%") },
  commentContent: { flex: 1, marginLeft: wp("4%") },
  commentHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: hp("0.6%") },
  commentNameRow: { flexDirection: "row", alignItems: "center" },
  commentName: { fontSize: hp("1.9%"), fontWeight: "700", color: "#1F2937", marginRight: wp("1.5%") },
  commentUser: { fontSize: hp("1.6%"), color: "#6B7280" },
  commentDate: { fontSize: hp("1.6%"), fontWeight: "500", color: "#9CA3AF" },
  commentMsg: { fontSize: hp("1.9%"), fontWeight: "500", color: "#111827" },
  hr: { height: 1, backgroundColor: "rgba(255,255,255,0.7)", marginVertical: hp("1.2%") },

  navWrap: { display: 'none' },
  navPill: { display: 'none' },


  // Setting
  groupCard: {
    borderRadius: 20,
    paddingVertical: hp("1.8%"),
    paddingHorizontal: wp("4%"),
    marginBottom: hp("2%"),
  },
  groupTitle: { fontSize: hp("2.1%"), fontWeight: "700", color: "#BE123C", marginBottom: hp("1.2%") },
  settingRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: hp("1%") },
  settingDivider: { borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.6)" },
  settingRowPressed: { opacity: 0.7 },
  settingTextWrap: { flex: 1, paddingRight: wp("3%") },
  settingLabel: { fontSize: hp("1.9%"), fontWeight: "700", color: "#7F1D1D" },
  settingDescription: { fontSize: hp("1.6%"), color: "#4B5563", marginTop: hp("0.2%") },
  toggleMock: {
    width: wp("12%"),
    height: hp("3%"),
    borderRadius: hp("1.5%"),
    backgroundColor: "rgba(255,255,255,0.75)",
    justifyContent: "center",
    padding: hp("0.3%"),
  },
  toggleDot: {
    width: hp("2.2%"),
    height: hp("2.2%"),
    borderRadius: hp("1.1%"),
    backgroundColor: "#CC7861",
    alignSelf: "flex-end",
  },
  supportCard: {
    borderRadius: 20,
    paddingVertical: hp("1.8%"),
    paddingHorizontal: wp("4%"),
    flexDirection: "row",
    alignItems: "center",
    marginTop: hp("1%"),
  },
  supportTextWrap: { marginLeft: wp("3%"), flex: 1 },
  supportTitle: { fontSize: hp("2%"), fontWeight: "700", color: "#BE123C" },
  supportSubtitle: { fontSize: hp("1.7%"), color: "#4B5563", marginTop: hp("0.4%") },

  // Layout
  safe: { flex: 1, backgroundColor: "#FFF8F6" },
  scroll: { flex: 1 },
  headerGradient: {
    paddingTop: hp("1.8%"),
    paddingBottom: hp("2.2%"),
    paddingHorizontal: wp("4.5%"),
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    width: wp("10%"),
    height: wp("10%"),
    borderRadius: wp("5%"),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.22)",
  },
  backButtonPressed: { backgroundColor: "rgba(255,255,255,0.36)" },
  headerCenter: { flex: 1, alignItems: "center", justifyContent: "center" },
  headerTitle: { fontSize: hp("2.6%"), fontWeight: "700", color: "#FFF5F2" },
  headerSubtitle: { fontSize: hp("1.7%"), color: "#FFE4E1", marginTop: hp("0.4%") },
  rightPlaceholder: { width: wp("10%") },
  content: {
    paddingHorizontal: wp("4.5%"),
    paddingTop: hp("2.5%"),
    paddingBottom: hp("5%"),
  },

  // Search
  searchBar: {
    borderRadius: 18,
    paddingVertical: hp("1.4%"),
    paddingHorizontal: wp("4%"),
    flexDirection: "row",
    alignItems: "center",
    marginBottom: hp("2.2%"),
  },
  searchTexts: { marginLeft: wp("3%") },
  searchPlaceholder: { fontSize: hp("1.9%"), color: "#7F1D1D", fontWeight: "700", marginBottom: hp("0.2%") },
  searchHint: { fontSize: hp("1.6%"), color: "#6B7280" },
  filterRow: { flexDirection: "row", flexWrap: "wrap", marginBottom: hp("2.2%") },
  filterChip: {
    paddingHorizontal: wp("3.5%"),
    paddingVertical: hp("0.6%"),
    borderRadius: 999,
    backgroundColor: "rgba(204,120,97,0.12)",
    marginRight: wp("2%"),
    marginBottom: hp("1%"),
  },
  filterChipPressed: { backgroundColor: "rgba(204,120,97,0.22)" },
  filterChipText: { fontSize: hp("1.7%"), color: "#7F1D1D", fontWeight: "600" },
  sectionCard: {
    borderRadius: 20,
    paddingVertical: hp("1.8%"),
    paddingHorizontal: wp("4%"),
    marginBottom: hp("2.4%"),
  },
  sectionTitle: { fontSize: hp("2.1%"), fontWeight: "700", color: "#BE123C", marginBottom: hp("1%") },
  keywordWrap: { flexDirection: "row", flexWrap: "wrap", marginTop: hp("0.6%") },
  keywordChip: {
    paddingHorizontal: wp("3.5%"),
    paddingVertical: hp("0.6%"),
    borderRadius: 999,
    backgroundColor: "#FFF",
    marginRight: wp("2%"),
    marginBottom: hp("1%"),
  },
  keywordChipPressed: { backgroundColor: "rgba(255,255,255,0.7)" },
  keywordText: { fontSize: hp("1.7%"), color: "#CC7861", fontWeight: "600" },
  recentRow: { flexDirection: "row", alignItems: "center", marginBottom: hp("0.8%") },
  recentText: { fontSize: hp("1.8%"), color: "#374151", marginLeft: wp("2.4%") },

  // Profile
  headerCard: {
    borderRadius: 22,
    paddingVertical: hp("2%"),
    paddingHorizontal: wp("4%"),
    flexDirection: "row",
    alignItems: "center",
    marginBottom: hp("2.4%"),
  },
  avatarLarge: {
    width: wp("18%"),
    height: wp("18%"),
    borderRadius: wp("9%"),
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: wp("4%"),
  },
  headerText: { flex: 1 },
  shopName: { fontSize: hp("2.4%"), fontWeight: "700", color: "#7F1D1D", marginBottom: hp("0.6%") },
  shopSubtitle: { fontSize: hp("1.7%"), color: "#4B5563", marginBottom: hp("1.2%") },
  updateBadge: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.7)",
    borderRadius: 999,
    paddingHorizontal: wp("3%"),
    paddingVertical: hp("0.5%"),
  },
  updateBadgePressed: { backgroundColor: "rgba(255,255,255,0.9)" },
  updateBadgeText: { fontSize: hp("1.6%"), color: "#BE123C", fontWeight: "600", marginLeft: wp("1.5%") },
  section: { marginBottom: hp("2.6%") },
  sectionTitle: { fontSize: hp("2.1%"), fontWeight: "700", color: "#BE123C", marginBottom: hp("1.2%") },
  inputShell: {
    backgroundColor: "#FFF",
    borderRadius: 16,
    paddingVertical: hp("1.2%"),
    paddingHorizontal: wp("4%"),
    marginBottom: hp("1%"),
    borderWidth: 1,
    borderColor: "rgba(204,120,97,0.2)",
  },
  inputLabel: { fontSize: hp("1.6%"), color: "#9F1239", fontWeight: "600", marginBottom: hp("0.4%") },
  inputValue: { fontSize: hp("1.8%"), color: "#1F2937" },
  noteCard: {
    borderRadius: 18,
    paddingVertical: hp("1.6%"),
    paddingHorizontal: wp("4%"),
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: hp("2.4%"),
  },
  noteText: { flex: 1, fontSize: hp("1.7%"), color: "#374151", marginLeft: wp("3%") },
  saveButton: {
    backgroundColor: "#CC7861",
    borderRadius: 18,
    paddingVertical: hp("1.6%"),
    alignItems: "center",
    justifyContent: "center",
    marginBottom: hp("1%"),
  },
  saveButtonPressed: { backgroundColor: "#B35E48" },
  saveButtonText: { color: "#FFF", fontSize: hp("2%"), fontWeight: "700" },

  // product-create
  uploadCard: {
    borderRadius: 22,
    paddingVertical: hp("1.8%"),
    paddingHorizontal: wp("4%"),
    flexDirection: "row",
    alignItems: "center",
    marginBottom: hp("2.4%"),
  },
  uploadIcon: {
    width: wp("12%"),
    height: wp("12%"),
    borderRadius: wp("6%"),
    backgroundColor: "rgba(255,255,255,0.7)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: wp("3%"),
  },
  uploadTexts: { flex: 1 },
  uploadTitle: { fontSize: hp("2%"), fontWeight: "700", color: "#7F1D1D" },
  uploadSubtitle: { fontSize: hp("1.7%"), color: "#4B5563", marginTop: hp("0.2%") },
  uploadButton: {
    backgroundColor: "#FFF",
    paddingHorizontal: wp("4%"),
    paddingVertical: hp("0.8%"),
    borderRadius: 999,
  },
  uploadButtonPressed: { backgroundColor: "rgba(255,255,255,0.75)" },
  uploadButtonText: { fontSize: hp("1.7%"), color: "#BE123C", fontWeight: "700" },
  inputPlaceholder: { fontSize: hp("1.8%"), color: "#9CA3AF" },
  shippingCard: {
    borderRadius: 20,
    paddingVertical: hp("1.8%"),
    paddingHorizontal: wp("4%"),
    flexDirection: "row",
    alignItems: "center",
    marginBottom: hp("2.6%"),
  },
  shippingTexts: { marginLeft: wp("3%"), flex: 1 },
  shippingTitle: { fontSize: hp("2%"), fontWeight: "700", color: "#7F1D1D" },
  shippingSubtitle: { fontSize: hp("1.7%"), color: "#4B5563", marginTop: hp("0.2%") },
  publishButton: {
    backgroundColor: "#CC7861",
    borderRadius: 18,
    paddingVertical: hp("1.6%"),
    alignItems: "center",
    marginBottom: hp("1%"),
  },
  publishButtonPressed: { backgroundColor: "#B35E48" },
  publishButtonText: { color: "#FFF", fontSize: hp("2%"), fontWeight: "700" },
  draftButton: {
    borderRadius: 18,
    paddingVertical: hp("1.4%"),
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(204,120,97,0.4)",
    marginBottom: hp("1%"),
  },
  draftButtonPressed: { backgroundColor: "rgba(204,120,97,0.1)" },
  draftButtonText: { color: "#CC7861", fontSize: hp("1.9%"), fontWeight: "700" },

  // Notifications
  summaryCard: {
    borderRadius: 20,
    paddingVertical: hp("1.8%"),
    paddingHorizontal: wp("4%"),
    flexDirection: "row",
    alignItems: "center",
    marginBottom: hp("2.4%"),
  },
  summaryTextWrap: { marginLeft: wp("3%"), flex: 1 },
  summaryTitle: { fontSize: hp("2.1%"), fontWeight: "700", color: "#BE123C" },
  summarySubtitle: { fontSize: hp("1.7%"), color: "#4B5563", marginTop: hp("0.4%") },
  listSection: { marginBottom: hp("2.6%") },
  alertCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    borderRadius: 18,
    paddingVertical: hp("1.6%"),
    paddingHorizontal: wp("4%"),
    marginBottom: hp("1.2%"),
  },
  alertIcon: { marginRight: wp("3%"), marginTop: hp("0.4%") },
  alertContent: { flex: 1 },
  alertType: { fontSize: hp("1.7%"), color: "#9F1239", fontWeight: "600", marginBottom: hp("0.4%") },
  alertMessage: { fontSize: hp("1.8%"), color: "#374151", lineHeight: hp("2.4%") },
  alertTime: { fontSize: hp("1.6%"), color: "#9CA3AF", marginTop: hp("0.6%") },
  reminderCard: { borderRadius: 20, paddingVertical: hp("2%"), paddingHorizontal: wp("4.5%") },
  reminderRow: { flexDirection: "row", alignItems: "center", paddingVertical: hp("0.6%") },
  reminderDivider: { borderTopWidth: 1, borderTopColor: "rgba(190,18,60,0.2)" },
  reminderText: { fontSize: hp("1.8%"), color: "#374151", marginLeft: wp("2.4%"), flex: 1 },

  // Messages
  highlightBanner: {
    borderRadius: 20,
    paddingVertical: hp("1.8%"),
    paddingHorizontal: wp("4%"),
    flexDirection: "row",
    alignItems: "center",
    marginBottom: hp("2.4%"),
  },
  bannerTextWrap: { marginLeft: wp("3%"), flex: 1 },
  bannerTitle: { fontSize: hp("2.1%"), fontWeight: "700", color: "#BE123C", marginBottom: hp("0.4%") },
  bannerSubtitle: { fontSize: hp("1.7%"), color: "#4B5563" },
  conversationCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    borderRadius: 18,
    paddingVertical: hp("1.6%"),
    paddingHorizontal: wp("4%"),
    marginBottom: hp("1.6%"),
  },
  avatar: { width: wp("12%"), height: wp("12%"), borderRadius: wp("6%"), backgroundColor: "#FFF", marginRight: wp("3%") },
  conversationContent: { flex: 1 },
  conversationHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: hp("0.6%") },
  conversationName: { fontSize: hp("2%"), fontWeight: "700", color: "#1F2937" },
  conversationUsername: { fontSize: hp("1.6%"), color: "#6B7280", marginTop: hp("0.2%") },
  conversationTime: { fontSize: hp("1.6%"), color: "#9CA3AF" },
  conversationSnippet: { fontSize: hp("1.8%"), color: "#374151", marginTop: hp("0.4%") },
  unreadBadge: {
    minWidth: wp("6%"),
    paddingHorizontal: wp("2%"),
    paddingVertical: hp("0.4%"),
    borderRadius: 999,
    backgroundColor: "#CC7861",
    alignItems: "center",
    justifyContent: "center",
  },
  unreadText: { color: "#FFF", fontSize: hp("1.6%"), fontWeight: "700" },

  // Dashboard
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: hp("2.5%"),
  },
  statCard: {
    width: "48%",
    borderRadius: 18,
    paddingVertical: hp("2%"),
    paddingHorizontal: wp("4%"),
    marginBottom: hp("1.8%"),
  },
  statIconWrap: {
    width: wp("10%"),
    height: wp("10%"),
    borderRadius: wp("5%"),
    backgroundColor: "rgba(255,255,255,0.7)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: hp("1.2%"),
  },
  statLabel: { fontSize: hp("1.7%"), color: "#7F1D1D", fontWeight: "600" },
  statValue: { fontSize: hp("2.2%"), color: "#581C1C", fontWeight: "700", marginTop: hp("0.4%") },
  chartCard: {
    borderRadius: 20,
    paddingVertical: hp("2.4%"),
    paddingHorizontal: wp("5%"),
    marginBottom: hp("2.5%"),
  },
  chartHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  chartTitle: { fontSize: hp("2.1%"), fontWeight: "700", color: "#BE123C" },
  chartPeriod: { fontSize: hp("1.7%"), color: "#9F1239", fontWeight: "600" },
  chartPlaceholder: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    height: hp("16%"),
    marginTop: hp("2%"),
    marginBottom: hp("1.4%"),
  },
  chartBarLarge: { width: "12%", height: "100%", borderRadius: 12, backgroundColor: "rgba(255,255,255,0.85)" },
  chartBarMedium: { width: "12%", height: "70%", borderRadius: 12, backgroundColor: "rgba(255,255,255,0.7)" },
  chartBarSmall: { width: "12%", height: "45%", borderRadius: 12, backgroundColor: "rgba(255,255,255,0.55)" },
  chartHint: { fontSize: hp("1.6%"), color: "#6B7280" },
  highlights: { marginBottom: hp("1%") },
  highlightCard: {
    borderRadius: 18,
    paddingVertical: hp("2.2%"),
    paddingHorizontal: wp("4.5%"),
    marginBottom: hp("1.6%"),
  },
  highlightTitle: { fontSize: hp("2%"), fontWeight: "700", color: "#BE123C", marginBottom: hp("0.8%") },
  highlightDescription: { fontSize: hp("1.7%"), color: "#4B5563", lineHeight: hp("2.4%") },
  ordersButton: { borderRadius: 22, overflow: "hidden" },
  ordersButtonPressed: { opacity: 0.85 },
  ordersButtonInner: {
    borderRadius: 22,
    paddingVertical: hp("1.8%"),
    paddingHorizontal: wp("4%"),
    flexDirection: "row",
    alignItems: "center",
  },
  ordersButtonIcon: {
    width: wp("11%"),
    height: wp("11%"),
    borderRadius: wp("5.5%"),
    backgroundColor: "rgba(255,255,255,0.7)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: wp("3%"),
  },
  ordersButtonTextWrap: { flex: 1 },
  ordersButtonTitle: { fontSize: hp("2%"), fontWeight: "700", color: "#7F1D1D" },
  ordersButtonSubtitle: { fontSize: hp("1.7%"), color: "#4B5563", marginTop: hp("0.2%") },
});